#include "include.h"
#include "macros.h"

#ifndef MAIN_CONFIG
	#define MAIN_CONFIG
		enum EVENT_CODE
		{
			NULL_EVENT_CODE,
			CLOSE_EVENT_CODE,
			START_EVENT_CODE,
			RESTART_EVENT_CODE,
			CHANGE_PLACE_TO_NEXT_EVENT_CODE,
			BRUSH_FOOD_EVENT_CODE,
			BRUSH_WALL_EVENT_CODE,
			BRUSH_EMPTY_EVENT_CODE,
			LEFT_MOUSE_PRESS_EVENT_CODE,
			RIGHT_MOUSE_PRESS_EVENT_CODE,
			MOUSE_SCROLL_UP_EVENT_CODE,
			MOUSE_SCROLL_DOWN_EVENT_CODE
		};

		enum PLACES
		{
			FOOD_PLACE,
			WALL_PLACE,
			EMPTY_PLACE,
			ANTHILL_PLACE,
			ANT_PLACE,
		};
#endif